"""
クラッシュ・ロワイヤル カード名 英語→日本語 変換辞書
"""

CARD_NAME_EN_TO_JA: dict[str, str] = {
    # --- ユニット (コモン) ---
    "Archers": "アーチャー",
    "Barbarians": "バーバリアン",
    "Bats": "コウモリの群れ",
    "Bomber": "ボンバー",
    "Elite Barbarians": "エリートバーバリアン",
    "Fire Spirit": "ファイアスピリット",
    "Firecracker": "ファイアクラッカー",
    "Goblins": "ゴブリン",
    "Ice Spirit": "アイススピリット",
    "Knight": "ナイト",
    "Minion Horde": "ガーゴイルの群れ",
    "Minions": "ガーゴイル",
    "Royal Giant": "ロイヤルジャイアント",
    "Royal Hogs": "ロイヤルホグ",
    "Royal Recruits": "ロイヤルリクルート",
    "Skeleton Army": "スケルトン部隊",
    "Skeleton Barrel": "スケルトンバレル",
    "Skeleton Dragons": "スケルトンドラゴン",
    "Skeletons": "スケルトン",
    "Spear Goblins": "槍ゴブリン",
    "Wall Breakers": "ウォールブレイカー",
    # --- ユニット (レア) ---
    "Battle Healer": "バトルヒーラー",
    "Battle Ram": "攻城バーバリアン",
    "Dart Goblin": "ダートゴブリン",
    "Elixir Golem": "エリクサーゴーレム",
    "Flying Machine": "フライングマシン",
    "Giant": "ジャイアント",
    "Goblin Gang": "ゴブリンギャング",
    "Guards": "ガード",
    "Heal Spirit": "ヒールスピリット",
    "Hog Rider": "ホグライダー",
    "Ice Golem": "アイスゴーレム",
    "Mega Minion": "メガガーゴイル",
    "Mini P.E.K.K.A": "ミニP.E.K.K.A",
    "Musketeer": "マスケット銃士",
    "Three Musketeers": "三銃士",
    "Valkyrie": "バルキリー",
    "Wizard": "ウィザード",
    "Zappies": "ザッピー",
    # --- ユニット (エピック) ---
    "Baby Dragon": "ベビードラゴン",
    "Balloon": "エアバルーン",
    "Bowler": "ボウラー",
    "Cannon Cart": "キャノンカート",
    "Dark Prince": "ダークプリンス",
    "Electro Dragon": "エレクトロドラゴン",
    "Electro Spirit": "エレクトロスピリット",
    "Executioner": "エクスキューショナー",
    "Giant Skeleton": "ジャイアントスケルトン",
    "Goblin Giant": "ゴブリンジャイアント",
    "Golem": "ゴーレム",
    "Goblin Drill": "ゴブリンドリル",
    "Hunter": "ハンター",
    "P.E.K.K.A": "P.E.K.K.A",
    "Prince": "プリンス",
    "Rascals": "ならず者",
    "Witch": "ネクロマンサー",
    # --- ユニット (レジェンダリー) ---
    "Bandit": "バンデット",
    "Electro Wizard": "エレクトロウィザード",
    "Fisherman": "フィッシャーマン",
    "Ghost": "ロイヤルゴースト",
    "Graveyard": "グレイブヤード",
    "Ice Wizard": "アイスウィザード",
    "Inferno Dragon": "インフェルノドラゴン",
    "Lava Hound": "ラヴァハウンド",
    "Lumberjack": "ランバージャック",
    "Magic Archer": "マジックアーチャー",
    "Mega Knight": "メガナイト",
    "Miner": "ディガー",
    "Mother Witch": "マザーネクロマンサー",
    "Night Witch": "ナイトウィッチ",
    "Phoenix": "フェニックス",
    "Princess": "プリンセス",
    "Ram Rider": "ラムライダー",
    "Royal Ghost": "ロイヤルゴースト",
    "Sparky": "スパーキー",
    "Electro Giant": "エレクトロジャイアント",
    # --- チャンピオン ---
    "Archer Queen": "アーチャークイーン",
    "Golden Knight": "ゴールドナイト",
    "Little Prince": "リトルプリンス",
    "Mighty Miner": "マイティマイナー",
    "Monk": "モンク",
    "Skeleton King": "スケルトンキング",
    # --- 呪文 ---
    "Arrows": "矢の雨",
    "Clone": "クローン",
    "Earthquake": "アースクエイク",
    "Fireball": "ファイアボール",
    "Freeze": "フリーズ",
    "Giant Snowball": "巨大雪玉",
    "Lightning": "ライトニング",
    "Mirror": "ミラー",
    "Poison": "ポイズン",
    "Rage": "レイジ",
    "Rocket": "ロケット",
    "Royal Delivery": "ロイヤルデリバリー",
    "The Log": "ローリングウッド",
    "Tornado": "トルネード",
    "Zap": "ザップ",
    "Barbarian Barrel": "バーバリアンの小樽",
    "Goblin Barrel": "ゴブリンバレル",
    # --- 建物 ---
    "Barbarian Hut": "バーバリアンの小屋",
    "Bomb Tower": "ボムタワー",
    "Cannon": "大砲",
    "Elixir Collector": "エリクサーポンプ",
    "Furnace": "ファーネス",
    "Goblin Cage": "ゴブリンの檻",
    "Goblin Hut": "ゴブリンの小屋",
    "Inferno Tower": "インフェルノタワー",
    "Mortar": "迫撃砲",
    "Tesla": "テスラ",
    "Tombstone": "墓石",
    "X-Bow": "クロスボウ",
    # --- 新カード (2024-2025追加) ---
    "Berserker": "バーサーカー",
    "Boss Bandit": "ボスバンデット",
    "Goblin Curse": "ゴブリンの呪い",
    "Goblin Demolisher": "ゴブリンデモリッシャー",
    "Goblin Machine": "ゴブリンマシン",
    "Goblinstein": "ゴブリンシュタイン",
    "Rune Giant": "ルーンジャイアント",
    "Spirit Empress": "スピリットエンプレス",
    "Suspicious Bush": "あやしい茂み",
    "Vines": "ツタ",
    "Void": "ヴォイド",
}


def translate_card(name_en: str) -> str:
    """英語カード名を日本語に変換する。辞書にない場合は英語名をそのまま返す。"""
    return CARD_NAME_EN_TO_JA.get(name_en.strip(), name_en.strip())


def translate_deck(deck_raw: str) -> str:
    """カンマ区切りのデッキ文字列を日本語に変換する。"""
    cards = deck_raw.split(",")
    return ", ".join(translate_card(c) for c in cards)
